var navOpenInBackgroundTab = 0x1000;
var oIE = new ActiveXObject("InternetExplorer.Application");
oIE.Navigate2("https://vkbexternal.partners.extranet.microsoft.com/vkbweb/?portalid=1");
oIE.Navigate2("https://kit.one.microsoft.com/", navOpenInBackgroundTab);
oIE.Navigate2("https://mspacsr.microsoft.com/", navOpenInBackgroundTab);
oIE.Navigate2("https://aka.ms/lmi", navOpenInBackgroundTab);
oIE.Navigate2("https://sharepoint.partners.extranet.microsoft.com/sites/GCS/commboard/Pages/Office-Decision-Tree-PIlot.aspx");
oIE.Navigate2("https://wue2.hotmail.com/default.aspx", navOpenInBackgroundTab);
oIE.Navigate2("https://gc.digitalriver.com/gc/ent/login.do", navOpenInBackgroundTab);
oIE.Navigate2("http://quickconnect.convergys.com/launch/", navOpenInBackgroundTab);
oIE.Navigate2("https://cvgsharepoint/sites/msoffice-mdc/ADO/Shared%20Documents/Forms/AllItems.aspx", navOpenInBackgroundTab);
oIE.Visible = true;